package com.example.JWTSpringBoot.Controller;


import com.example.JWTSpringBoot.JWTUtility.JwtUtil;
import com.example.JWTSpringBoot.Model.User;
import com.example.JWTSpringBoot.Model2.UserRequest;
import com.example.JWTSpringBoot.Model2.UserResponse;
import com.example.JWTSpringBoot.Repository.UserRepository;
import com.example.JWTSpringBoot.Service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
@RequestMapping("/user")
public class UserController {

    @Autowired
     private UserService userService;

    @Autowired
    private JwtUtil jwtUtil;

    @Autowired
    private AuthenticationManager authenticationManager;


    @PostMapping("/save")
    public ResponseEntity<String >saveuser(@RequestBody User user){
        Integer id = userService.saveUSer(user);
        String body= "User ' "+id+"' saved";
        return ResponseEntity.ok(body);
    }

    // validate user and generate token

     @PostMapping("/login")
    public ResponseEntity<UserResponse>loginUser
             (@RequestBody UserRequest userRequest)
     {
         authenticationManager.authenticate(new UsernamePasswordAuthenticationToken
                 (userRequest.getUsername(), userRequest.getPassword()));

        String token = jwtUtil.Generatetoken(userRequest.getUsername());
        return  ResponseEntity.ok(
                new UserResponse(token,"sucess! generated by shweta"));

    }

    //3 after login

    @PostMapping("/welcome")

    public ResponseEntity<String>accessdata(Principal p){
        return  ResponseEntity.ok("Hello User"+p.getName());
    }


}
